# Generated by Django 5.0.3 on 2024-09-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrador'), ('patient', 'Paciente'), ('specialist', 'Especialista')], default='patient', max_length=10),
        ),
    ]
